### ISSUE TITLE
Désigner les petits extraits

### ISSUE THREAD

**Issue by laxsmi** [laxsmi/maurandine#15]
Peut être qu'après 5 articles en "fullscreen scroll" on pourrait repasser sur un affichage plus compact (genre photo en petit + titre et extrait, sur deux colonnes)
![image](https://cloud.githubusercontent.com/assets/1422621/26358548/8197d38e-3f98-11e7-9f2f-3be8903c3128.png)

**Comment by Maucuenca** [comment]
D'accord ^^

**Comment by laxsmi** [comment]
en cours - section créée. Mais pb avec le footer qui n'apparait pas - recompter les divs et vérifier qu'ils sont bien tous fermés. Aussi vérifier que le fullpage scroll est bien triggeré au bon endroit...

**Comment by laxsmi** [comment]
Ok! Cf la règle article.small-excerpt dans la feuille de style.
