### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by Maucuenca** [laxsmi/maurandine#26]
il est trop gros, et trop présent

**Comment by laxsmi** [comment]
du coup ça va si j'y affiche "Ce site fonctionne sous Wordpress avec le thème Maurandine". Tu veux ajouter qqchose d'autre (un petit texte etc ?)

**Comment by Maucuenca** [comment]
Ouiii voilà ce que je veux : 
"Thème Maurandine - réalisé par Thomas et Maureen". Tu vois autre chose à ajouter ?

**Comment by laxsmi** [comment]
OK - pb de z-index à résoudre, le footer est derrière les autres calques et du coup on ne peut pas pas cliquer sur les liens
